#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accel,          sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Sensor, S1,     HTIRS2,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

task main(){

	//waitForStart(); //wait for autonomous phase

	while(true){
		nxtDisplayTextLine(1,"%d",nMotorEncoder[rightMotor]);
		nxtDisplayTextLine(2,"%d",nMotorEncoder[leftMotor]);

		nMotorEncoder[rightMotor] = 0;
		nMotorEncoder[leftMotor] = 0;54


		while(nMotorEncoder[rightMotor]<(1440)){
			motor[rightMotor] = 100;
			motor[leftMotor] = 100;
		}
		nMotorEncoder[rightMotor] = 0;
		nMotorEncoder[leftMotor] = 0;

		while(nMotorEncoder[rightMotor]<(1440*2)){
			motor[rightMotor] = 50;
			motor[leftMotor] = -50;
		}
		/*while(SensorValue[IR1] != 5){
		IR1value = SensorValue[IR1];
		nxtDisplayCenteredTextLine(5,"%d",IR1value);
		motor[rightMotor] = 20;
		motor[rightMotor] = -20;
		}*/

		nMotorEncoder[rightMotor] = 0;
		nMotorEncoder[leftMotor] = 0;
		while(nMotorEncoder[rightMotor]<(1440*5)){
			motor[rightMotor] = 100;
			motor[leftMotor] = 100;
		}
		motor[rightMotor] = 50;
		motor[leftMotor] = -50;
	}

	getJoystickSettings(joystick);
		motor(rightMotor) = joystick.joy1_y1;
 		motor(leftMotor) = joystick.joy1_y2;
// 		printf(motor(motorD));
 		wait1Msec(10000);

 		motor(rightMotor) = 0;
 		motor(leftMotor) = 0;


	}
